### ISSUE TITLE
Run cli command with `--samples 3` will trigger error

### ISSUE THREAD

**Issue by nogamenofun98** [harlan-zw/unlighthouse#60] opened 2023-05-09 02:33 UTC
### Describe the bug

After running a while, the cli response the following:

Error: Cannot create new tab, and no tabs already open.
    at C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\gather\connections\cri.js:45:35
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Driver.connect (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\gather\driver.js:119:5)
    at async Function.run (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\gather\gather-runner.js:484:7)
    at async Function._gatherArtifactsFromBrowser (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\runner.js:264:23)
    at async Function.gather (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\runner.js:170:21)
    at async lighthouse (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\index.js:50:21)
    at async file:///C:/Users/ant008/AppData/Local/npm-cache/_npx/9c5b11f5f0ea845b/node_modules/@unlighthouse/core/dist/process/lighthouse.mjs:16:26
Error: Cannot create new tab, and no tabs already open.
    at C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\gather\connections\cri.js:45:35
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Driver.connect (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\gather\driver.js:119:5)
    at async Function.run (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\gather\gather-runner.js:484:7)
    at async Function._gatherArtifactsFromBrowser (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\runner.js:264:23)
    at async Function.gather (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\runner.js:170:21)
    at async lighthouse (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\index.js:50:21)
    at async file:///C:/Users/ant008/AppData/Local/npm-cache/_npx/9c5b11f5f0ea845b/node_modules/@unlighthouse/core/dist/process/lighthouse.mjs:16:26
C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\gather\driver.js:348
      asyncTimeout = setTimeout(reject, timeout, new LHError(LHError.errors.PROTOCOL_TIMEOUT, {
                                                 ^

LighthouseError [LHError]: PROTOCOL_TIMEOUT
    at C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\gather\driver.js:348:50
    at new Promise (<anonymous>)
    at Driver.sendCommandToSession (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\gather\driver.js:346:28)
    at Driver.sendCommand (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\gather\driver.js:369:17)
    at Object.clearDataForOrigin (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\gather\driver\storage.js:58:19)
    at Function.disposeDriver (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\gather\gather-runner.js:179:39)
    at Function.run (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\gather\gather-runner.js:532:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Function._gatherArtifactsFromBrowser (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\runner.js:264:23)
    at async Function.gather (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\runner.js:170:21) {
  code: 'PROTOCOL_TIMEOUT',
  friendlyMessage: {
    i18nId: 'lighthouse-core/lib/lh-error.js | protocolTimeout',
    values: {
      errorCode: 'PROTOCOL_TIMEOUT',
      protocolMethod: 'Storage.clearDataForOrigin'
    },
    formattedDefault: 'Waiting for DevTools protocol response has exceeded the allotted time. (Method: Storage.clearDataForOrigin)'
  },
  lhrRuntimeError: true,
  protocolMethod: 'Storage.clearDataForOrigin'
}

Node.js v17.1.0

 ERROR  Failed to run lighthouse for route Command failed with exit code 1: node C:/Users/ant008/AppData/Local/npm-cache/_npx/9c5b11f5f0ea845b/node_modules/@unlighthouse/core/dist/process/lighthouse.mjs --cache=true --routeReport={"route":{"url":"https://next.syopex.com/brand/skll"},"artifactPath":"D:\\Frontend\\unlighthouse\\.unlighthouse\\next.syopex.com\\e6ae\\reports\\brand\\skll"} --lighthouseOptions={"onlyCategories":["performance","accessibility","best-practices","seo"],"throttlingMethod":"provided","throttling":{"rttMs":0,"throughputKbps":0,"cpuSlowdownMultiplier":1,"requestLatencyMs":0,"downloadThroughputKbps":0,"uploadThroughputKbps":0},"formFactor":"mobile","screenEmulation":{"mobile":true,"width":360,"height":640,"deviceScaleFactor":2}} --port=54889
Error: Cannot create new tab, and no tabs already open.
    at C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\gather\connections\cri.js:45:35
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Driver.connect (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\gather\driver.js:119:5)
    at async Function.run (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\gather\gather-runner.js:484:7)
    at async Function._gatherArtifactsFromBrowser (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\runner.js:264:23)
    at async Function.gather (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\runner.js:170:21)
    at async lighthouse (C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\index.js:50:21)
    at async file:///C:/Users/ant008/AppData/Local/npm-cache/_npx/9c5b11f5f0ea845b/node_modules/@unlighthouse/core/dist/process/lighthouse.mjs:16:26
C:\Users\ant008\AppData\Local\npm-cache\_npx\9c5b11f5f0ea845b\node_modules\lighthouse\lighthouse-core\gather\driver.js:348
      asyncTimeout = setTimeout(reject, timeout, new LHError(LHError.errors.PROTOCOL_TIMEOUT, {

### Reproduction

npx unlighthouse-puppeteer --site next.syopex.com --samples 3 OR npx unlighthouse --site next.syopex.com --samples 3

### System / Nuxt Info

```Shell
System:
    OS: Windows 10 10.0.19045
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 7.24 GB / 15.92 GB
  Binaries:
    Node: 17.1.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.35)
    Internet Explorer: 11.0.19041.1566
```

**Comment by briantully** [comment] 2023-05-13 04:21
Same here using the unlighthouse command with an unlighthouse.config.ts file with scanner.samples 3 set.

Reproduction
unlighthouse 

System / Nuxt Info
System:
    OS: macOS 12.6.5 
    CPU: Apple M1 Max
    Memory: 32 GB
  Binaries:
    Node: 16.20.0
    npm: 9.6.6
  Browsers:
    Chrome Version 113.0.5672.92 (Official Build) (arm64)

**Comment by harlan-zw** [comment] 2023-05-14 08:32
Hi, thanks for the issue :)

This may be resolved with Unlighthouse 0.7.0 with the updated Puppeteer dependency. If it still doesn't work you can try to pass the config: `chrome.useSystem: false` and use the fallback Chrome installer.

**Comment by nogamenofun98** [comment] 2023-05-16 02:55
> Hi, thanks for the issue :)
> 
> I am not able to replicate it personally, though this may be resolved with Unlighthouse 0.7.0 with the updated Puppeteer dependency. If it still doesn't work you can try to pass the config: `chrome.useSystem: false` and use the fallback Chrome installer.

I tried to put `chrome.useSystem:false` in the unlighthouse config file, it did download a fallback chrome automatically but still response the same error. I also tried to manually point it to my local chrome installation (both chrome and edge tested), and it also response same error.

Here is my config:
```
export default {
  puppeteerClusterOptions: {
      // only run 1 worker at a time 
    maxConcurrency: 1
  },
  puppeteerOptions: {
    executablePath: 'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe'
  }
}
```

**Comment by harlan-zw** [comment] 2023-05-18 16:18
Sorry I'd like to help further but I can't replicate on my Linux laptop, if any Windows users have capacity to help me debug it would be appreicated.

**Comment by NathanBeddoeWebDev** [comment] 2023-05-23 00:10
I saw this issue when I tried sampling, I'll see if I can debug it and figure out what the issue is.

**Comment by harlan-zw** [comment] 2023-05-23 04:33
I have made two attempts to upgrade so far, it hasn't been very successful as there's many breaking changes (cjs support is dropped). Will attempt again soon .

**Comment by broskees** [comment] 2023-06-25 00:57
Just ran into this issue myself. Seems related to [this](https://github.com/GoogleChrome/lighthouse/issues/14930).

**Comment by OliCote** [comment] 2023-07-26 17:59
Just to give more information about the problem, it also occurs for me on MacOS

```
System:
    OS: MacOs Monterey 12.1
  Binaries:
    Node: 18.17.0
    npm: 9.4.1
  Browsers:
    Chrome(Version 114.0.5735.248)
```

**Comment by mwskwong** [comment] 2024-02-17 02:30
IUnderstanding this is a Lighthouse 9 issue.

> I have made two attempts to upgrade so far, it hasn't been very successful as there's many breaking changes (cjs support is dropped). Will attempt again soon .

I'm really looking forward to this. This is especially important in CI environment since the CPU/Memory power varies in quite a lot when running against multiple pages. Without `samples`, it is really hard to set a meaningful budget to warn about performance issue.

**Comment by 842u** [comment] 2024-02-19 15:20
The problem can be resolved by bumping the version of the Lighthouse package inside @unlighthouse/core.

https://github.com/harlan-zw/unlighthouse/pull/183 made that changes to the codebase. However, the current version (v0.10.6) still uses Lighthouse (^9.6.8) so we may need to wait for the new version release.

For those interested, here's a GitHub workflow [file](https://github.com/842u/car-service/commit/efaaa93865e834dbceb658fb1e34f6fd2f3a8943#diff-79816c6377fb874cc36324b25782978c3c6f95a9b171d09a04a15b57644f96c8) where the Lighthouse version is manually updated.

**Comment by mwskwong** [comment] 2024-02-29 02:00
> The problem can be resolved by bumping the version of the Lighthouse package inside @unlighthouse/core.
> 
> #183 made that changes to the codebase. However, the current version (v0.10.6) still uses Lighthouse (^9.6.8) so we may need to wait for the new version release.
> 
> For those interested, here's a GitHub workflow [file](https://github.com/842u/car-service/commit/efaaa93865e834dbceb658fb1e34f6fd2f3a8943#diff-79816c6377fb874cc36324b25782978c3c6f95a9b171d09a04a15b57644f96c8) where the Lighthouse version is manually updated.

Just tried this. Though `--samples` can be used now, I noticed that Lighthouse crashes fairly frequently. Not sure whether this is related to the compatibility with the current `@unlighthouse/core` implementation.

**Closed** 2024-03-01 01:55 UTC
Labels: bug, help wanted
