### ISSUE TITLE
Unlighthouse stuck at "Waiting for routes..." screen

### ISSUE THREAD

**Issue by mef** [harlan-zw/unlighthouse#66] opened 2023-05-09 07:55 UTC
### Describe the bug

unlighthouse dashboard does not load any data, and no error message at all is ever displayed, when using on a Linux distribution with Chromium installed. The default browser on this machine is Firefox.

The problem happens regardless of the website scanned.

`unlighthouse-puppeteer` behaves exactly the same way.

### How to reproduce

1. Run `unlighthouse` as instructed in the documentation:
```
npx unlighthouse --site https://my-website.com
```
2. Confirm the npx prompt to install required package.

### Observed result

* In the command line, messages confirm the successful connection to the website with status `200`, the eventual detection of a sitemap, and number of routes initially discovered.
* In the command line, a deprecation warning is displayed:
```
  Puppeteer old Headless deprecation warning:
    In the near feature `headless: true` will default to the new Headless mode
    for Chrome instead of the old Headless implementation. For more
    information, please see https://developer.chrome.com/articles/new-headless/.
    Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
    If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.
```
* A tab open in the default web browser and loads unlighthouse dashboard
* The dashboard stays empty with `Waiting for routes...` spinner displayed. Worker progress value remains at 0%, even minutes after the launch.

### Expected result

* In the command line, messages confirm the successful connection to the website with status `200`, the eventual detection of a sitemap, and number of routes initially discovered.
* A tab open in the default web browser and loads unlighthouse dashboard
* The dashboard content gets populated progressively as the crawling progresses.

### Reproduction

c.f. bug description

### System / Nuxt Info

```Shell
System:
    OS: Linux 4.19 BunsenLabs GNU/Linux 10.5 (Lithium)
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 9.83 GB / 15.35 GB
    Container: Yes
    Shell: 5.0.3 - /bin/bash
  Binaries:
    Node: 16.19.1 - ~/.nvm/versions/node/v16.19.1/bin/node
    npm: 8.19.3 - ~/.nvm/versions/node/v16.19.1/bin/npm
  Browsers:
    Chromium: 90.0.4430.212
    Firefox: 112.0.2
```

**Comment by harlan-zw** [comment] 2023-05-12 09:39
Hi @mef, thanks for the issue.

This may be fixed in 0.6.0, if not could you please provide the URL you're scanning and I can dig further into it?

**Comment by piotr-musialek-footballco** [comment] 2023-05-12 13:28
For me it got stuck even in 0.6.0:
<img width="522" alt="image" src="https://github.com/harlan-zw/unlighthouse/assets/112651766/94673d65-ec29-4b6c-bb77-5ce27aed01ef">

**Comment by mef** [comment] 2023-05-12 17:17
> This may be fixed in 0.6.0, if not could you please provide the URL you're scanning and I can dig further into it?

The problem is still here for me using 0.6.0. It happens on any domain, I just tried with `example.com`.

**Comment by harlan-zw** [comment] 2023-05-14 08:36
> > This may be fixed in 0.6.0, if not could you please provide the URL you're scanning and I can dig further into it?
> 
> The problem is still here for me using 0.6.0. It happens on any domain, I just tried with `example.com`.

Hey, can you try out version 0.7.0 with the `--debug` option and provide the output? I am not able to replicate

`npx unlighthouse@0.7.0 --site example.com --debug`

**Comment by harlan-zw** [comment] 2023-05-14 08:36
> For me it got stuck even in 0.6.0: <img alt="image" width="522" src="https://user-images.githubusercontent.com/112651766/237984267-94673d65-ec29-4b6c-bb77-5ce27aed01ef.png">

This should perform a little better in 0.7.0 but this site has quite a complex i18n structure that I don't think Unlighthouse can handle in its current state.

**Comment by mef** [comment] 2023-05-14 16:39
> Hey, can you try out version 0.7.0 with the --debug option and provide the output? I am not able to replicate

Thanks for the follow-up. Here is the debug log output:

```
$ npx unlighthouse@0.7.1 --site example.com --debug --no-cache
Need to install the following packages:
  unlighthouse@0.7.1
Ok to proceed? (y) 
(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠹ idealTree:f748e5d196c066c9: timing idealTree:#root Completed in 57ms

(#########⠂⠂⠂⠂⠂⠂⠂⠂⠂) ⠸ idealTree:f748e5d196c066c9: timing idealTree:#root Completed in 57ms



npm WARN deprecated intl-messageformat-parser@1.8.1: We've written a new parser that's 6x faster and is backwards compatible. Please use @formatjs/icu-messageformat-parser
⚙ Starting Unlighthouse at root: /tmp cwd: /tmp                                                                      unlighthouse 18:33:35
⚙ Discovered config definition { config: undefined, sources: [] }                                                    unlighthouse 18:33:35
⚙ Unable to locale page files, disabling route discovery.                                                            unlighthouse 18:33:35
ℹ Using system chrome located at: /usr/bin/chromium.                                                                 unlighthouse 18:33:35
⚙ Post config resolution { routerPrefix: '/',                                                                        unlighthouse 18:33:35
  apiPrefix: '/api',
  cache: false,
  client:
   { groupRoutesKey: 'route.definition.name',
     columns:
      { overview: [Array],
        performance: [Array],
        accessibility: [Array],
        'best-practices': [Array],
        seo: [Array] } },
  scanner:
   { customSampling: {},
     ignoreI18nPages: true,
     maxRoutes: 200,
     skipJavascript: true,
     samples: 1,
     throttle: false,
     crawler: true,
     dynamicSampling: 5,
     sitemap: true,
     robotsTxt: true,
     device: 'mobile' },
  server: { port: 5678, showURL: false, open: true },
  discovery: false,
  root: '/tmp',
  outputPath: '.unlighthouse',
  debug: true,
  puppeteerOptions:
   { headless: true,
     ignoreHTTPSErrors: true,
     defaultViewport:
      { mobile: true, width: 412, height: 823, deviceScaleFactor: 1.75, disabled: false },
     executablePath: '/usr/bin/chromium' },
  puppeteerClusterOptions:
   { monitor: true,
     workerCreationDelay: 500,
     retryLimit: 3,
     timeout: 300000,
     maxConcurrency: 8,
     skipDuplicateUrls: false,
     retryDelay: 2000,
     concurrency: 3,
     puppeteer:
      PuppeteerNode {
        _changedProduct: false,
        _isPuppeteerCore: true,
        connect: [Function: bound bound connect],
        configuration: [Object],
        defaultBrowserRevision: '113.0.5672.63',
        launch: [Function: bound launch],
        executablePath: [Function: bound executablePath],
        defaultArgs: [Function: bound defaultArgs] } },
  lighthouseOptions:
   { onlyCategories: [ 'performance', 'accessibility', 'best-practices', 'seo' ],
     throttlingMethod: 'provided',
     throttling:
      { rttMs: 0,
        throughputKbps: 0,
        cpuSlowdownMultiplier: 1,
        requestLatencyMs: 0,
        downloadThroughputKbps: 0,
        uploadThroughputKbps: 0 },
     formFactor: 'mobile',
     screenEmulation:
      { mobile: true, width: 412, height: 823, deviceScaleFactor: 1.75, disabled: false } },
  urls: [],
  site: 'https://example.com',
  hooks: { 'resolved-config': [AsyncFunction: resolved-config] },
  chrome:
   { useSystem: true,
     useDownloadFallback: true,
     downloadFallbackVersion: 1095492,
     downloadFallbackCacheDir: '/home/user/.unlighthouse' } }
⚙ Testing Site https://example.com is valid.                                                                         unlighthouse 18:33:35
✔ Successfully connected to https://example.com. (Status: 200).                                                      unlighthouse 18:33:36
⚙ Creating Unlighthouse                                                                                              unlighthouse 18:33:36
⚙ Setting Unlighthouse Site URL [Site: https://example.com]                                                          unlighthouse 18:33:36
⚙ Setting Unlighthouse Server Context [Server: http://localhost:5678/]                                               unlighthouse 18:33:36
› Creating new Unrouted ctx: unlighthouse-api {                                                                  unlighthouse-api 18:33:36
  debug: true,
  prefix: '/',
  middleware: [],
  hooks: {
    'serve:before-route': [Function: serve:before-route]
  },
  plugins: [
    {
      meta: [Object],
      setup: [AsyncFunction: setup]
    }
  ],
  presets: [
    {
      meta: [Object],
      setup: [AsyncFunction: setup]
    },
    {
      meta: [Object],
      setup: [AsyncFunction: setup]
    }
  ],
  name: 'unlighthouse-api',
  app: {
    use: [Function: use],
    handler: [AsyncFunction (anonymous)] {
      __is_handler__: true
    },
    stack: [],
    options: {}
  }
}
› Using preset: @unrouted/preset-api@0.5.0                                                                       unlighthouse-api 18:33:36
› Using preset: @unrouted/preset-node@0.5.0                                                                      unlighthouse-api 18:33:36
› Using plugin: lazyRouteHandles                                                                                 unlighthouse-api 18:33:36
› Registering route get /__lighthouse.                                                                           unlighthouse-api 18:33:36
› Registering route post /api/reports/rescan.                                                                    unlighthouse-api 18:33:36
› Registering route post /api/reports/:id/rescan.                                                                unlighthouse-api 18:33:36
› Registering route get,head /api/__launch.                                                                      unlighthouse-api 18:33:36
› Registering route get,head /api/ws.                                                                            unlighthouse-api 18:33:36
› Registering route get,head /api/reports.                                                                       unlighthouse-api 18:33:36
› Registering route get,head /api/scan-meta.                                                                     unlighthouse-api 18:33:36
› Registering route get /**.                                                                                     unlighthouse-api 18:33:36
› Registering route get /.                                                                                       unlighthouse-api 18:33:36
› Setting up 9 routes.                                                                                           unlighthouse-api 18:33:36
⚙ cache is disabled, deleting cache folder: .unlighthouse                                                            unlighthouse 18:33:36
⚙ Starting Unlighthouse [Server: http://localhost:5678/ Site: https://example.com Debug: true]                       unlighthouse 18:33:36
⚙ Scanning https://example.com/robots.txt                                                                            unlighthouse 18:33:36

 WARN  You seem to be missing a robots.txt.                                                                          unlighthouse 18:33:37

⚙ Attempting to fetch sitemap at https://example.com/sitemap.xml                                                     unlighthouse 18:33:37
Error occurred during "crawl('https://example.com/sitemap.xml')":
 Error: HTTP Error occurred: Response code 404 (Not Found)
⚙ Fetched sitemap with 0 URLs.                                                                                       unlighthouse 18:33:37
ℹ Sitemap appears to be missing, falling back to crawler mode.                                                       unlighthouse 18:33:37
⚙ Route has been queued. Path: / Name: _index.                                                                       unlighthouse 18:33:37
› GET /api/scan-meta 200 object - 0ms                                                                            unlighthouse-api 18:33:38

   ╭───────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                           │
   │   ⛵  Unlighthouse cli @ v0.7.1                                                           │
   │                                                                                           │
   │   ▸ Scanning: https://example.com                                                         │
   │   ▸ Route Discovery: Crawler                                                              │
   │                                                                                           │
   │    💖 Like Unlighthouse? Support the development: https://github.com/sponsors/harlan-zw   │
   │                                                                                           │
   │   Report: http://localhost:5678/                                                          │
   │                                                                                           │
   ╰───────────────────────────────────────────────────────────────────────────────────────────╯

› GET /favicon.ico 200 undefined - 1ms                                                                           unlighthouse-api 18:33:39
› GET /api/scan-meta 200 object - 0ms                                                                            unlighthouse-api 18:33:39
› GET /api/reports 200 object - 0ms                                                                              unlighthouse-api 18:33:39
› GET /api/scan-meta 200 object - 0ms                                                                            unlighthouse-api 18:33:43
› GET /api/scan-meta 200 object - 0ms                                                                            unlighthouse-api 18:33:44
› GET /api/scan-meta 200 object - 1ms                                                                            unlighthouse-api 18:33:48
› GET /api/scan-meta 200 object - 0ms                                                                            unlighthouse-api 18:33:49

```

**Comment by StampixSMO** [comment] 2023-05-17 07:55
I have a similar error. My CI flow kept running for 6 hours because unlighthouse never exited. There's an issue where the tested server is unavailable, which is out of scope here, but I don't think unlighthouse should hang when the server under test is unreachable? 

Here's my log extract:

<details>
<summary>Details</summary>

```
> storefront@0.1.0 unlighthouse:test /Users/X/X/X/apps/storefront
> unlighthouse-ci --debug

⚙ Starting Unlighthouse at root: /Users/X/X/X/apps/storefront cwd: /Users/X/X/X/apps/storefront                             unlighthouse 9:51:51 AM
⚙ Discovered config definition { config: { site: 'http://localhost:8080', ci: { buildStatic: true, budget: [Object] } },                                    unlighthouse 9:51:52 AM
  sources: [ '/Users/X/X/X/apps/storefront/unlighthouse.config.ts' ] }
⚙ Unable to locale page files, disabling route discovery.                                                                                                   unlighthouse 9:51:52 AM
ℹ Using system chrome located at: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome.                                                             unlighthouse 9:51:52 AM
⚙ Post config resolution { routerPrefix: '/',                                                                                                               unlighthouse 9:51:52 AM
  apiPrefix: '/api',
  cache: false,
  client:
   { groupRoutesKey: 'route.definition.name',
     columns:
      { overview: [Array],
        performance: [Array],
        accessibility: [Array],
        'best-practices': [Array],
        seo: [Array] } },
  scanner:
   { customSampling: {},
     ignoreI18nPages: true,
     maxRoutes: 200,
     skipJavascript: true,
     samples: 1,
     throttle: false,
     crawler: true,
     dynamicSampling: 5,
     sitemap: true,
     robotsTxt: true,
     device: 'mobile' },
  server: { port: 5678, showURL: false, open: true },
  discovery: false,
  root: '/Users/X/X/X/apps/storefront',
  outputPath: '.unlighthouse',
  debug: true,
  puppeteerOptions:
   { headless: true,
     ignoreHTTPSErrors: true,
     defaultViewport:
      { mobile: true, width: 412, height: 823, deviceScaleFactor: 1.75, disabled: false },
     executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' },
  puppeteerClusterOptions:
   { monitor: true,
     workerCreationDelay: 500,
     retryLimit: 3,
     timeout: 300000,
     maxConcurrency: 10,
     skipDuplicateUrls: false,
     retryDelay: 2000,
     concurrency: 3,
     puppeteer:
      PuppeteerNode {
        _changedProduct: false,
        _isPuppeteerCore: true,
        connect: [Function: bound bound connect],
        configuration: [Object],
        defaultBrowserRevision: '113.0.5672.63',
        launch: [Function: bound launch],
        executablePath: [Function: bound executablePath],
        defaultArgs: [Function: bound defaultArgs] } },
  lighthouseOptions:
   { onlyCategories: [ 'performance', 'accessibility', 'best-practices', 'seo' ],
     throttlingMethod: 'provided',
     throttling:
      { rttMs: 0,
        throughputKbps: 0,
        cpuSlowdownMultiplier: 1,
        requestLatencyMs: 0,
        downloadThroughputKbps: 0,
        uploadThroughputKbps: 0 },
     formFactor: 'mobile',
     screenEmulation:
      { mobile: true, width: 412, height: 823, deviceScaleFactor: 1.75, disabled: false } },
  urls: [],
  ci:
   { budget: { performance: 90, accessibility: 90, 'best-practices': 90, seo: 90 },
     buildStatic: true },
  hooks: { 'resolved-config': [AsyncFunction: resolved-config] },
  site: 'http://localhost:8080/',
  chrome:
   { useSystem: true,
     useDownloadFallback: true,
     downloadFallbackVersion: 1095492,
     downloadFallbackCacheDir: '/Users/X/.unlighthouse' } }
⚙ Testing Site http://localhost:8080/ is valid.                                                                                                             unlighthouse 9:51:52 AM

 WARN  Request to site http://localhost:8080/ threw an unhandled exception. Please check the URL is valid. connect ECONNREFUSED 127.0.0.1:8080              unlighthouse 9:51:52 AM

  at Function.AxiosError.from (/Users/X/X/X/node_modules/.pnpm/axios@1.4.0/node_modules/axios/lib/core/AxiosError.js:89:14)
  at RedirectableRequest.handleRequestError (/Users/X/X/X/node_modules/.pnpm/axios@1.4.0/node_modules/axios/lib/adapters/http.js:591:25)
  at RedirectableRequest.emit (node:events:520:28)
  at ClientRequest.eventHandlers.<computed> (/Users/X/X/X/node_modules/.pnpm/follow-redirects@1.15.2/node_modules/follow-redirects/index.js:14:24)
  at ClientRequest.emit (node:events:520:28)
  at Socket.socketErrorListener (node:_http_client:442:9)
  at Socket.emit (node:events:520:28)
  at emitErrorNT (node:internal/streams/destroy:157:8)
  at emitErrorCloseNT (node:internal/streams/destroy:122:3)
  at processTicksAndRejections (node:internal/process/task_queues:83:21)


 ERROR  Site check failed. will attempt to proceed but may fail.                                                                                            unlighthouse 9:51:52 AM

⚙ Creating Unlighthouse using config from /Users/X/X/X/apps/storefront/unlighthouse.config.ts                                               unlighthouse 9:51:52 AM
⚙ Setting Unlighthouse Site URL [Site: http://localhost:8080/]                                                                                              unlighthouse 9:51:52 AM
⚙ Setting Unlighthouse CI Context [Site: http://localhost:8080/]                                                                                            unlighthouse 9:51:52 AM
⚙ cache is disabled, deleting cache folder: .unlighthouse                                                                                                   unlighthouse 9:51:52 AM
⚙ Starting Unlighthouse [Server: N/A Site: http://localhost:8080/ Debug: true]                                                                              unlighthouse 9:51:52 AM
⚙ Scanning http://localhost:8080/robots.txt                                                                                                                 unlighthouse 9:51:52 AM

 WARN  You seem to be missing a robots.txt.                                                                                                                 unlighthouse 9:51:52 AM

⚙ Attempting to fetch sitemap at http://localhost:8080/sitemap.xml                                                                                          unlighthouse 9:51:52 AM
Error occurred during "crawl('http://localhost:8080/sitemap.xml')":
 Error: Error occurred: RequestError
⚙ Fetched sitemap with 0 URLs.                                                                                                                              unlighthouse 9:51:55 AM
ℹ Sitemap appears to be missing, falling back to crawler mode.                                                                                              unlighthouse 9:51:55 AM
⚙ Route has been queued. Path: / Name: _index.                                                                                                              unlighthouse 9:51:55 AM
⚙ HTML extract of http://localhost:8080/ response failed.                                                                                                   unlighthouse 9:51:55 AM
ℹ Skipping /. Invalid response from URL http://localhost:8080/ code: 404.                                                                                   unlighthouse 9:51:55 AM
⚙ Ignoring route /.                                     
```

</details>

**Comment by harlan-zw** [comment] 2023-05-18 17:01
If you're using Windows and WSL, these notes may help provided by someone else:

- I added an unlighthouse.config.ts file like you suggested (can't remember if this alone fixed the issue, but for reference I also:)
- Installed Puppeteer on WSL as their docs suggests https://pptr.dev/troubleshooting#running-puppeteer-on-wsl-windows-subsystem-for-linux
- Installed Chrome in WSL like Windows suggests https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps#install-google-chrome-for-linux

**Comment by StampixSMO** [comment] 2023-05-19 14:33
@harlan-zw The site does not work, but Unlighthouse hangs, which should not happen. It should just say the site is unreachable and quit, right?

**Comment by harlan-zw** [comment] 2023-05-22 04:37
If you see the output it should warn you that the site is not accessible. It continues in this state because there may be instances where the initial site check fails but the rest of the functionality works correctly.

**Comment by StampixSMO** [comment] 2023-05-22 13:21
> If you see the output it should warn you that the site is not accessible. It continues in this state because there may be instances where the initial site check fails but the rest of the functionality works correctly. 

Sure, but surely it is unintended behaviour that this would cause a CI to run indefinitely?

**Comment by adevade** [comment] 2023-11-30 13:21
If I install `unlighthouse` into a local project it seems to work actually, but I would like to have it installed globally if possible?

**Comment by saif71** [comment] 2023-12-19 10:42
OK. Found a solution!
You need to have the "Chorme" installed on your system. **Not the beta / dev / canary** but the normal **chrome browser.** 
After that run the unlighthouse again and it works.

**Comment by nekromoff** [comment] 2024-02-07 14:08
Still happens to me with   ⛵  Unlighthouse cli @ v0.10.6
```
› GET /api/scan-meta 200 object - 0ms                                                                   unlighthouse-api 15:07:20
› GET /api/scan-meta 200 object - 0ms                                                                   unlighthouse-api 15:07:21
› GET /api/scan-meta 200 object - 0ms                                                                   unlighthouse-api 15:07:25
› GET /api/scan-meta 200 object - 1ms                                                                   unlighthouse-api 15:07:26
› GET /api/scan-meta 200 object - 0ms                                                                   unlighthouse-api 15:07:30
› GET /api/scan-meta 200 object - 0ms                                                                   unlighthouse-api 15:07:31
```
nothing else happens.

Maybe an option to specify browser to use? Chromium is commonly installed on Ubuntu, but yet it seems that Unlighthouse fails without Chrome installed.

**Comment by masonbrothers** [comment] 2024-02-14 17:35
> > If you see the output it should warn you that the site is not accessible. It continues in this state because there may be instances where the initial site check fails but the rest of the functionality works correctly.
> 
> Sure, but surely it is unintended behaviour that this would cause a CI to run indefinitely?

I am having that issue right now. I am trying to use unlighthouse in a CI pipeline and it hangs indefinitely. Perhaps there is some kind of timeout?

It is a bit of a hack, but I am trying to do this:
```bash
unlighthouse-ci --site http://localhost:3000 --budget 50 --build-static --disable-sitemap  2>&1 | tee >(grep -q "Site check failed" && echo "Terminating unlighthouse" && pkill -P $$) 
```

**Comment by masonbrothers** [comment] 2024-02-14 17:35
It is a bit of a hack, but this should be a workaround:
```bash
unlighthouse-ci --site http://localhost:3000 --budget 50 --build-static --disable-sitemap  2>&1 | tee >(grep -q "Site check failed" && echo "Terminating unlighthouse" && pkill -P $$) 
```

**Comment by saif71** [comment] 2024-02-16 18:48
> > OK. Found a solution! You need to have the "Chorme" installed on your system. **Not the beta / dev / canary** but the normal **chrome browser.** After that run the unlighthouse again and it works.
> 
> I have chromium and I thought this would be enough, do I really need to install Chrome?

In my experience, you really need to install chrome.

**Comment by harlan-zw** [comment] 2024-03-03 05:18
This issue has gone a bit off-topic, going to close. If you're having the error from the OP please make a new issue with your site details.

**Closed by harlan-zw** 2024-03-03 05:18 UTC

**Comment by Yuniac** [comment] 2024-03-17 14:56
> > OK. Found a solution! You need to have the "Chorme" installed on your system. **Not the beta / dev / canary** but the normal **chrome browser.** After that run the unlighthouse again and it works.
> 
> I have chromium and I thought this would be enough, do I really need to install Chrome?


I had to install chrome to get it to work
